### ISSUE TITLE
correct machine identification is broken on JHub

### ISSUE THREAD

**Issue by matt-long** [NCAR/ncar-jobqueue#7]
`NCARCluster` is returning `LocalCluster` on JupyterHub on Cheyenne. At the very least, we should throw a warning.

**Comment by matt-long** [comment]
@jbaksta if you have a minute, can you help with this? We use regex to detect the system we're on. This is probably fragile. Is there a more robust way to do this via environment variables?

https://github.com/NCAR/ncar-jobqueue/blob/bb2258509d46eafa7e9592cbed88edf17decddc7/ncar_jobqueue/cluster.py#L7

**Comment by andersy005** [comment]
Related to #5

**Comment by jbaksta** [comment]
@matt-long 

Apologies, I've been out on travel. Is there a specific kernel this is happening under? I put together a small test case of what happens in the _cluster.py_ file, but just returning strings and it seems to function in a regular Python 3 kernel. Attach a screenshot perhaps of this running somewhere?

Additionally, instead of relying on a cluster node shortname, it may be better to use the `socket.getfqdn()` and look at the output of that (i.e., on cheyenne it should return similar to 'r6i6n32.ib0.cheyenne.ucar.edu' and on casper it would still return 'casper01' or such. Ideally, from the sysadmin viewpoint, a cluster should be identifiable by a domain name and short name, but getting the full name gives you more to work with.

**Comment by jbaksta** [comment]
![Screen Shot 2019-06-10 at 10 18 41 AM](https://user-images.githubusercontent.com/2792834/59209724-3e9fd580-8b69-11e9-80fd-14900d92b18d.png)

**Comment by matt-long** [comment]
Thanks @jbaksta. I am not able to reproduce the problem either—however, I did personally witness this not working for a user. I don't know the details of their configuration/kernel.
